[package]
name = "xr_passthrough_layer"
description = "impl of XR_FB_passthrough as an API layer"
authors = ["Yuxuan Shui <yshuiv7@gmail.com>"]
repository = "https://github.com/yshui/xr_passthrough_layer"
version = "0.1.0"
edition = "2024"
license = "MIT"

[workspace]
members = [ "thirdparty/quark", "thirdparty/quark/proc-macros", "hello", "experiment" , "xrhelper", "xtask"]

[workspace.dependencies]
vulkano = "0.35"
vulkano-shaders = "0.35"
anyhow = { version = "1.0", features = ["backtrace"] }
openxr = "0.21"
nalgebra = "0.34"
serde = { version = "1.0", features = ["derive"] }
ioctl = { version = "0.31.2", features = ["ioctl"] }
log = "0.4"
env_logger = "0.11"
itertools = "0.14"
v4l = "0.14"
ash = "0.38"
glam = "0.32"
smallvec = "1.15"
smallvec2 = { version = "=2.0.0-alpha.12", package = "smallvec" }
xdg = "3.0.0"
xr = { path = "./xrhelper" }
shaderc = "0.10"
bytemuck = { version = "1.25", features = ["derive"] }
renderdoc = "0.12"
ctrlc = "3.5"
winit = "0.30"
phf = { version = "0.13", features = ["macros"] }

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anyhow.workspace = true
vulkano.workspace = true
vulkano-shaders.workspace = true
openxr.workspace = true
nalgebra.workspace = true
serde.workspace = true
log.workspace = true
env_logger.workspace = true
itertools.workspace = true
v4l.workspace = true
ash.workspace = true
glam.workspace = true
smallvec.workspace = true
smallvec2.workspace = true
xdg.workspace = true
bytemuck.workspace = true
renderdoc.workspace = true

image = "0.25.1"
ed25519-dalek = { version = "3.0.0-pre.0", features = ["rand_core"] }
udev = "0.9.3"
thiserror = "2.0.11"
config = "0.15.8"
argh = "0.1.6"
serde_json = "1.0.70"
toml = "1"
humantime-serde = "1.0.1"
libloading = "0.9.0"
quark = { path = "thirdparty/quark" }
rand = "0.10.0-rc.5"
arc-swap = "1.7.1"
phf.workspace = true
nix = { version = "0.31.2", features = ["ioctl", "fs"] }
flate2 = { version = "1.1.9", features = ["zlib"] }

[build-dependencies]
anyhow.workspace = true
shaderc.workspace = true
